Perform\BaseBundle\Entity\ResetToken:
    type: entity
    table: perform_base_reset_token
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
        secret:
            type: string
        expiresAt:
            type: datetime
    manyToOne:
        user:
            targetEntity: User
            joinColumn:
                nullable: false
