Perform\BaseBundle\Entity\Setting:
    type: entity
    table: perform_base_setting
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
        key:
            type: string
            column: key_name
        value:
            type: text
            nullable: true
        defaultValue:
            type: text
            nullable: true
        type:
            type: string
        requiredRole:
            type: string
            nullable: true
        global:
            type: boolean
    manyToOne:
        user:
            targetEntity: Symfony\Component\Security\Core\User\UserInterface
            joinColumn:
                nullable: true
