Perform\BaseBundle\Entity\Tag:
    type: entity
    table: perform_base_tag
    repositoryClass: Perform\BaseBundle\Repository\TagRepository
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
        title:
            type: string
        discriminator:
            type: string
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
