perform_base_password_forgot:
    path: /reset-password
    defaults:
        _controller: PerformBaseBundle:Password:forgotPassword

perform_base_password_reset:
    path: /reset-password/{id}/{secret}
    defaults:
        _controller: PerformBaseBundle:Password:resetPassword

perform_base_password_success:
    path: /reset-password/success
    defaults:
        _controller: PerformBaseBundle:Password:success
