services:
    perform_base.listener.login:
        class: Perform\BaseBundle\EventListener\LoginListener
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - {name: kernel.event_listener, event: security.interactive_login, method: onLogin}

    perform_base.admin.user:
        class: Perform\BaseBundle\Admin\UserAdmin
        tags:
            - {name: perform_base.admin, entity: "PerformBaseBundle:User"}

    perform_base.menu_link.users:
        class: Perform\BaseBundle\Menu\SimpleLinkProvider
        arguments:
            - 'users'
            - 'PerformBaseBundle:User'
            - null
            - 'users'
        tags:
            - { name: perform_base.link_provider, alias: users }

    perform_base.doctrine.user_listener:
        class: Perform\BaseBundle\Doctrine\UserListener
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_subscriber }

    perform_base.importer.user:
        class: Perform\BaseBundle\Importer\UserImporter
        arguments: ["@doctrine.orm.entity_manager"]
