imports:
    - { resource: services_actions.yml }
    - { resource: services/field_types.yml }

services:
    perform_base.crud.registry:
        class: Perform\BaseBundle\Crud\CrudRegistry
        arguments:
            - '@perform_base.doctrine.entity_resolver'
            - '@doctrine.orm.entity_manager'

    perform_base.config_store:
        class: Perform\BaseBundle\Config\ConfigStore
        arguments:
            - '@perform_base.doctrine.entity_resolver'
            - '@perform_base.crud.registry'
            - '@perform_base.type_registry'
            - '@perform_base.action_registry'
            - '@security.authorization_checker'

    perform_base.voter.crud:
        class: Perform\BaseBundle\Security\CrudVoter
        arguments:
            - '@perform_base.crud.registry'
            - '@perform_base.routing.crud_generator'
            - '@doctrine.orm.entity_manager'
        tags:
            - security.voter

    perform_base.form.type.crud:
        class: Perform\BaseBundle\Form\Type\CrudType
        arguments:
            - '@perform_base.config_store'
            - '@perform_base.type_registry'
        tags:
            - {name: form.type}

    perform_base.form.type.datepicker:
        class: Perform\BaseBundle\Form\Type\DatePickerType
        arguments:
            - "@perform_base.asset_container"
        tags:
            - {name: form.type}

    perform_base.doctrine.entity_resolver:
        class: Perform\BaseBundle\Doctrine\EntityResolver
        arguments: ['%perform_base.entity_aliases%', '%perform_base.extended_entities%']

    perform_base.doctrine.repository_resolver:
        class: Perform\BaseBundle\Doctrine\RepositoryResolver
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@perform_base.doctrine.entity_resolver'
    Perform\BaseBundle\Doctrine\RepositoryResolver: '@perform_base.doctrine.repository_resolver'

    perform_base.data_collector.crud:
        class: Perform\BaseBundle\DataCollector\CrudDataCollector
        public: false
        arguments:
            - '@perform_base.crud.registry'
            - '@perform_base.config_store'
            - '@security.access.decision_manager'
            - '%perform_base.extended_entities%'
        tags:
            -
                name: data_collector
                template: '@PerformBase/data_collector/crud.html.twig'
                id: 'perform_base.crud'

    perform_base.asset_container:
        class: Perform\BaseBundle\Asset\AssetContainer

    perform_base.routing.crud_loader:
        class: Perform\BaseBundle\Routing\CrudLoader
        public: false
        arguments: ['@perform_base.crud.registry']
        tags:
            - {name: routing.loader}

    perform_base.routing.crud_generator:
        class: Perform\BaseBundle\Routing\CrudUrlGenerator
        arguments: ['@router']

    perform_base.routing.checker:
        class: Perform\BaseBundle\Routing\RouteChecker
        arguments:
            - "@router"

    perform_base.listener.crud_template:
        class: Perform\BaseBundle\EventListener\CrudTemplateListener
        arguments: ['@service_container']
        tags:
            -
                name: kernel.event_listener
                event: kernel.controller
                method: onKernelController
                priority: -200

    perform_base.template_populator:
        class: Perform\BaseBundle\Crud\TemplatePopulator
        arguments:
            - "@perform_base.config_store"
            - "@perform_base.crud.registry"
            - "@event_dispatcher"

    perform_base.context_renderer:
        class: Perform\BaseBundle\Crud\ContextRenderer
        arguments:
            - '@perform_base.type_registry'
            - '@twig'

    perform_base.twig.crud:
        class: Perform\BaseBundle\Twig\Extension\CrudExtension
        arguments:
            - '@perform_base.context_renderer'
            - '@perform_base.config_store'
            - '@perform_base.routing.crud_generator'
            - '@request_stack'
        tags:
            - {name: twig.extension}

    perform_base.twig.action:
        class: Perform\BaseBundle\Twig\Extension\ActionExtension
        arguments:
            - "@router"
            - "@perform_base.routing.crud_generator"
            - "@perform_base.action_registry"
            - "@perform_base.config_store"
        tags:
            - {name: twig.extension}

    perform_base.twig.export:
        class: Perform\BaseBundle\Twig\Extension\ExportExtension
        arguments:
            - "@router"
            - "@perform_base.config_store"
        tags:
            - {name: twig.extension}
            - {name: kernel.event_listener, method: onKernelRequest, event: kernel.request}

    perform_base.twig.util:
        class: Perform\BaseBundle\Twig\Extension\UtilExtension
        arguments:
            - "@perform_base.routing.checker"
        tags:
            - {name: twig.extension}

    perform_base.twig.asset:
        class: Perform\BaseBundle\Twig\Extension\AssetExtension
        arguments: ["@perform_base.asset_container"]
        tags:
            - {name: twig.extension}

    perform_base.menu_builder:
        class: Perform\BaseBundle\Menu\MenuBuilder
        arguments:
            - '@knp_menu.factory'
            - '@event_dispatcher'
        tags:
            - { name: knp_menu.menu_builder, method: createSidebar, alias: perform_sidebar }

    perform_base.menu_extension.crud:
        class: Perform\BaseBundle\Menu\Extension\CrudExtension
        arguments: ['@perform_base.routing.crud_generator']
        tags:
            # higher priority than routing extension at 0
            - { name: knp_menu.factory_extension, priority: 1}

    perform_base.menu_renderer:
        class: Knp\Menu\Renderer\TwigRenderer
        arguments:
            - '@twig'
            - '@@PerformBase/_menu.html.twig'
            - '@knp_menu.matcher'
            - { currentClass: 'active' }
        tags:
            - { name: knp_menu.renderer, alias: perform_sidebar }

    perform_base.listener.settings_menu:
        class: Perform\BaseBundle\EventListener\SettingsMenuListener
        arguments:
            - '@perform_base.routing.checker'
        tags:
            - { name: kernel.event_listener, event: perform_base.menu.build, method: onMenuBuild }

    perform_base.doctrine.extend_listener:
        class: Perform\BaseBundle\Doctrine\ExtendEntitiesListener
        arguments:
            - "%perform_base.extended_entities%"
        tags:
            - { name: doctrine.event_subscriber }

    perform_base.doctrine.resolve_listener:
        class: Perform\BaseBundle\Doctrine\ResolveEntitiesListener
        arguments:
            - "%perform_base.resolved_entities%"
        tags:
            - { name: doctrine.event_subscriber }

    perform_base.selector.entity:
        class: Perform\BaseBundle\Selector\EntitySelector
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"
            - "@perform_base.config_store"

    perform_base.listener.list_query.sort:
        class: Perform\BaseBundle\EventListener\SortListQueryListener
        arguments:
            - "@perform_base.config_store"
        tags:
            - {name: kernel.event_listener, event: perform_base.crud.list_query, method: onListQuery}

    perform_base.listener.list_query.filter:
        class: Perform\BaseBundle\EventListener\FilterListQueryListener
        arguments:
            - "@perform_base.config_store"
            - "@perform_base.selector.entity"
        tags:
            - {name: kernel.event_listener, event: perform_base.crud.list_query, method: onListQuery}
            - {name: kernel.event_listener, event: perform_base.crud.list_context, method: onListContext}

    perform_base.entity_manager:
        class: Perform\BaseBundle\Crud\EntityManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"
            - "@logger"

    perform_base.asset_strategy:
        class: Symfony\Component\Asset\VersionStrategy\StaticVersionStrategy
        public: false
        arguments:
            - "%perform_base.auto_asset_version%"

    perform_base.settings_importer:
        class: Perform\BaseBundle\Settings\SettingsImporter
        arguments: ["@doctrine.orm.entity_manager"]

    perform_base.settings_manager:
        class: Perform\BaseBundle\Settings\SettingsManager
        arguments: ["@doctrine.orm.entity_manager"]

    perform_base.settings_panel_registry:
        class: Perform\BaseBundle\Settings\SettingsPanelRegistry
        arguments: ["@twig", []]

    perform_base.settings.account:
        class: Perform\BaseBundle\Settings\AccountPanel
        tags:
            - { name: perform_base.settings_panel, alias: account }

    perform_base.markdown:
        class: League\CommonMark\CommonMarkConverter

    perform_base.bundle_searcher:
        class: Perform\BaseBundle\Util\BundleSearcher
        arguments:
            - "@kernel"

    perform_base.form.type.hidden_entity:
        class: Perform\BaseBundle\Form\Type\HiddenEntityType
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - {name: form.type}

    perform_base.export.writer_factory:
        class: Perform\BaseBundle\Exporter\WriterFactory

    perform_base.exporter:
        class: Perform\BaseBundle\Exporter\Exporter
        arguments:
            - '@perform_base.config_store'
            - '@perform_base.selector.entity'
            - '@perform_base.type_registry'
            - '@perform_base.export.writer_factory'

    perform_base.asset.dumper:
        class: Perform\BaseBundle\Asset\Dumper\Dumper
        arguments:
            - '@filesystem'

    perform_base.warmer.assets:
        class: Perform\BaseBundle\CacheWarmer\AssetsWarmer
        arguments:
            - '@event_dispatcher'
            - '@perform_base.asset.dumper'
        tags:
            - {name: kernel.cache_warmer}

    perform_base.listener.assets:
        class: Perform\BaseBundle\EventListener\AssetsListener
        arguments:
            - '%kernel.project_dir%/asset-paths.js'
            - '%perform_base.assets.namespaces%'
            - '%perform_base.assets.entrypoints%'
            - '%perform_base.assets.extra_sass%'
            - '%perform_base.assets.extra_js%'
            - '%perform_base.assets.theme%'
        tags:
            - {name: kernel.event_listener, event: perform_base.asset_dump.add, method: onAddAssets}
