services:
    perform_base.listener.login:
        class: Perform\BaseBundle\EventListener\LoginListener
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - {name: kernel.event_listener, event: security.interactive_login, method: onLogin}
