imports:
    - { resource: services_actions.yml }

services:
    perform_base.admin.registry:
        class: Perform\BaseBundle\Admin\AdminRegistry
        arguments:
            - '@service_container'
            - '@perform_base.doctrine.entity_resolver'

    perform_base.config_store:
        class: Perform\BaseBundle\Config\ConfigStore
        arguments:
            - '@perform_base.doctrine.entity_resolver'
            - '@perform_base.admin.registry'
            - '@perform_base.type_registry'
            - '@perform_base.action_registry'
            - '@security.authorization_checker'

    perform_base.voter.crud:
        class: Perform\BaseBundle\Security\CrudVoter
        arguments:
            - '@perform_base.admin.registry'
            - '@perform_base.routing.crud_url'
        tags:
            - security.voter

    perform_base.form.type.admin:
        class: Perform\BaseBundle\Form\Type\AdminType
        arguments:
            - '@perform_base.config_store'
            - '@perform_base.doctrine.entity_resolver'
            - '@perform_base.type_registry'
        tags:
            - {name: form.type}

    perform_base.form.type.datepicker:
        class: Perform\BaseBundle\Form\Type\DatePickerType
        arguments:
            - "@perform_base.asset_container"
        tags:
            - {name: form.type}

    perform_base.doctrine.entity_resolver:
        class: Perform\BaseBundle\Doctrine\EntityResolver
        arguments: ['%perform_base.entity_aliases%', '%perform_base.extended_entities%']

    perform_base.admin_collector:
        class: Perform\BaseBundle\DataCollector\AdminsDataCollector
        public: false
        arguments:
            - '@perform_base.admin.registry'
            - '@perform_base.config_store'
            - '@security.access.decision_manager'
            - '%perform_base.extended_entities%'
        tags:
            -
                name: data_collector
                template: '@PerformBase/data_collector/admins.html.twig'
                id: 'perform_base.admins'

    perform_base.asset_container:
        class: Perform\BaseBundle\Asset\AssetContainer

    perform_base.routing.crud:
        class: Perform\BaseBundle\Routing\CrudLoader
        public: false
        arguments: ['@perform_base.admin.registry']
        tags:
            - {name: routing.loader}

    perform_base.routing.crud_url:
        class: Perform\BaseBundle\Routing\CrudUrlGenerator
        arguments: ['@perform_base.admin.registry', '@router']

    perform_base.listener.crud_template:
        class: Perform\BaseBundle\EventListener\CrudTemplateListener
        arguments: ['@service_container']
        tags:
            -
                name: kernel.event_listener
                event: kernel.controller
                method: onKernelController
                priority: -200

    perform_base.listener.ajax:
        class: Perform\BaseBundle\EventListener\AjaxListener
        tags:
            - {name: kernel.event_subscriber}

    perform_base.context_renderer:
        class: Perform\BaseBundle\Admin\ContextRenderer
        arguments:
            - '@perform_base.type_registry'
            - '@twig'

    perform_base.twig.crud:
        class: Perform\BaseBundle\Twig\Extension\CrudExtension
        arguments:
            - '@perform_base.context_renderer'
            - '@perform_base.routing.crud_url'
            - '@request_stack'
        tags:
            - {name: twig.extension}

    perform_base.twig.action:
        class: Perform\BaseBundle\Twig\Extension\ActionExtension
        arguments:
            - "@router"
            - "@perform_base.routing.crud_url"
            - "@perform_base.action_registry"
            - "@perform_base.config_store"
        tags:
            - {name: twig.extension}

    perform_base.twig.export:
        class: Perform\BaseBundle\Twig\Extension\ExportExtension
        arguments:
            - "@router"
            - "@perform_base.config_store"
        tags:
            - {name: twig.extension}
            - {name: kernel.event_listener, method: onKernelRequest, event: kernel.request}

    perform_base.twig.util:
        class: Perform\BaseBundle\Twig\Extension\UtilExtension
        arguments:
            - "@router"
            - '@perform_base.config_store'
        tags:
            - {name: twig.extension}

    perform_base.twig.asset:
        class: Perform\BaseBundle\Twig\Extension\AssetExtension
        arguments: ["@perform_base.asset_container"]
        tags:
            - {name: twig.extension}

    perform_base.menu_builder:
        class: Perform\BaseBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu_builder, method: createSidebar, alias: perform_sidebar }

    perform_base.menu_extension:
        class: Perform\BaseBundle\Menu\Extension\EntityExtension
        arguments: ['@perform_base.routing.crud_url']
        tags:
            # higher priority than routing extension at 0
            - { name: knp_menu.factory_extension, priority: 1}

    perform_base.menu_renderer:
        class: Knp\Menu\Renderer\TwigRenderer
        arguments:
            - '@twig'
            - '@@PerformBase/_menu.html.twig'
            - '@knp_menu.matcher'
            - { currentClass: 'active' }
        tags:
            - { name: knp_menu.renderer, alias: perform_sidebar }

    perform_base.menu_link.dashboard:
        class: Perform\BaseBundle\Menu\DashboardLinkProvider
        tags:
            - { name: perform_base.link_provider, alias: dashboard }

    perform_base.menu_link.settings:
        class: Perform\BaseBundle\Menu\SettingsLinkProvider
        tags:
            - { name: perform_base.link_provider, alias: settings }

    perform_base.email.mailer:
        class: Perform\BaseBundle\Email\Mailer
        arguments: ["@swiftmailer.mailer", "@twig", "%perform_base.mailer.from_address%", "@logger"]

    perform_base.doctrine.extend_listener:
        class: Perform\BaseBundle\Doctrine\ExtendEntitiesListener
        arguments:
            - "%perform_base.extended_entities%"
        tags:
            - { name: doctrine.event_subscriber }

    perform_base.selector.entity:
        class: Perform\BaseBundle\Selector\EntitySelector
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@perform_base.config_store"

    perform_base.entity_manager:
        class: Perform\BaseBundle\Manager\EntityManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"
            - "@logger"

    perform_base.asset_strategy:
        class: Symfony\Component\Asset\VersionStrategy\StaticVersionStrategy
        public: false
        arguments:
            - "%perform_base.auto_asset_version%"

    perform_base.settings_importer:
        class: Perform\BaseBundle\Settings\SettingsImporter
        arguments: ["@doctrine.orm.entity_manager"]

    perform_base.settings_manager:
        class: Perform\BaseBundle\Settings\SettingsManager
        arguments: ["@doctrine.orm.entity_manager"]

    perform_base.settings_panel_registry:
        class: Perform\BaseBundle\Settings\SettingsPanelRegistry
        arguments: ["@twig", []]

    perform_base.settings.account:
        class: Perform\BaseBundle\Settings\AccountPanel
        tags:
            - { name: perform_base.settings_panel, alias: account }

    perform_base.type.entity:
        class: Perform\BaseBundle\Type\EntityType
        arguments:
            - "@doctrine.orm.entity_manager"

    perform_base.type.collection:
        class: Perform\BaseBundle\Type\CollectionType
        arguments:
            - "@perform_base.admin.registry"
            - "@doctrine.orm.entity_manager"
            - "@perform_base.asset_container"

    perform_base.type.slug:
        class: Perform\BaseBundle\Type\SlugType
        arguments:
            - "@perform_base.asset_container"

    perform_base.bundle_searcher:
        class: Perform\BaseBundle\Util\BundleSearcher
        arguments:
            - "@kernel"

    perform_base.form.type.hidden_entity:
        class: Perform\BaseBundle\Form\Type\HiddenEntityType
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - {name: form.type}

    perform_base.export.writer_factory:
        class: Perform\BaseBundle\Exporter\WriterFactory

    perform_base.exporter:
        class: Perform\BaseBundle\Exporter\Exporter
        arguments:
            - '@perform_base.config_store'
            - '@perform_base.selector.entity'
            - '@perform_base.type_registry'
            - '@perform_base.export.writer_factory'

    perform_base.warmer.sass:
        class: Perform\BaseBundle\CacheWarmer\SassWarmer
        arguments:
            - '@perform_base.bundle_searcher'
            - '@filesystem'
            - '%perform_base.theme%'
            - '%perform_base.extra_sass%'
        tags:
            - {name: kernel.cache_warmer}
