services:
    perform_base.action_registry:
        class: Perform\BaseBundle\Action\ActionRegistry

    perform_base.action_runner:
        class: Perform\BaseBundle\Action\ActionRunner
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@perform_base.config_store"
            - "@security.authorization_checker"

    perform_base.action.delete:
        class: Perform\BaseBundle\Action\DeleteAction
        arguments:
            - "@perform_base.entity_manager"
        tags:
            - { name: perform_base.action, alias: perform_base_delete }

    Perform\BaseBundle\Controller\ActionController:
        arguments:
            - '@perform_base.action_runner'
            - '@perform_base.routing.crud_generator'
        tags:
            - controller.service_arguments
