services:
    Perform\BaseBundle\Command\InstallCommand:
        arguments:
        tags:
            - console.command

    Perform\BaseBundle\Command\GenerateAssetNamespacesCommand:
        arguments:
            - '@perform_base.asset.dumper'
            - '%kernel.project_dir%'
            - '%perform_base.assets.namespaces%'
        tags:
            - console.command
